### ISSUE TITLE
Unable to install pgsql-parser

### ISSUE THREAD

**Issue by DVGY** [constructive-io/pgsql-parser#126]
I am using WSL Ubuntu. Node v20.17.0 and npm 10.8.2. When I do npm i pgsql-parser
```
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm error code 1
npm error path /home/gaurav/testgit/node_modules/libpg-query
npm error command failed
npm error command sh -c node-pre-gyp install --fallback-to-build
npm error Failed to execute '/home/gaurav/.nvm/versions/node/v20.17.0/bin/node /home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node --module_name=queryparser --module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.11
npm error node-pre-gyp info using node@20.17.0 | linux | x64
npm error node-pre-gyp info check checked for "/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node" (not found)
npm error node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz
npm error node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz 
npm error node-pre-gyp WARN Pre-built binaries not installable for libpg-query@13.3.2 and node@20.17.0 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp info ok 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp http GET https://nodejs.org/download/release/v20.17.0/node-v20.17.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v20.17.0/node-v20.17.0-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v20.17.0/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v20.17.0/SHASUMS256.txt
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/testgit/node_modules/libpg-query/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/.cache/node-gyp/20.17.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/gaurav/.cache/node-gyp/20.17.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/gaurav/.cache/node-gyp/20.17.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/gaurav/testgit/node_modules/libpg-query',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info ok 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
npm error gyp ERR! stack at async loadConfigGypi (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
npm error gyp ERR! stack at async build (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
npm error gyp ERR! stack at async run (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
npm error gyp ERR! command "/home/gaurav/.nvm/versions/node/v20.17.0/bin/node" "/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node" "--module_name=queryparser" "--module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm error gyp ERR! cwd /home/gaurav/testgit/node_modules/libpg-query
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok 
npm error node-pre-gyp ERR! build error 
npm error node-pre-gyp ERR! stack Error: Failed to execute '/home/gaurav/.nvm/versions/node/v20.17.0/bin/node /home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node --module_name=queryparser --module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gaurav/testgit/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error node-pre-gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
npm error node-pre-gyp ERR! command "/home/gaurav/.nvm/versions/node/v20.17.0/bin/node" "/home/gaurav/testgit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm error node-pre-gyp ERR! cwd /home/gaurav/testgit/node_modules/libpg-query
npm error node-pre-gyp ERR! node -v v20.17.0
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm error node-pre-gyp ERR! not ok
npm error A complete log of this run can be found in: /home/gaurav/.npm/_logs/2024-09-26T17_59_43_475Z-debug-0.log
```

**Comment by 9hNguyen1432** [comment]
Let install `python3` and `g++` to solved it. 
```
sudo apt install python3
sudo apt install g++
```

**Comment by 9hNguyen1432** [comment]
The error shows that the pre-built binaries aren't available for your Node.js version (20.17.0), so the installation process is falling back to building from source, you need to install these build tools.
```
sudo apt install python3
sudo apt install g++
```

From sharing of my friend

**Comment by DVGY** [comment]
@9hNguyen1432 still getting same error

```
gaurav@DESKTOP-DQ92TU1:~/testgit$ npm install pgsql-parser
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm error code 1
npm error path /home/gaurav/testgit/node_modules/libpg-query
npm error command failed
npm error command sh -c node-pre-gyp install --fallback-to-build
npm error Failed to execute '/home/gaurav/.nvm/versions/node/v20.17.0/bin/node /home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node --module_name=queryparser --module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.11
npm error node-pre-gyp info using node@20.17.0 | linux | x64
npm error node-pre-gyp info check checked for "/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node" (not found)
npm error node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz
npm error node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz 
npm error node-pre-gyp WARN Pre-built binaries not installable for libpg-query@13.3.2 and node@20.17.0 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.2-node-v115-linux-x64.tar.gz 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp info ok 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/testgit/node_modules/libpg-query/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/gaurav/.cache/node-gyp/20.17.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/gaurav/.cache/node-gyp/20.17.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/gaurav/.cache/node-gyp/20.17.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/gaurav/testgit/node_modules/libpg-query',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info ok 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
npm error gyp ERR! stack at async loadConfigGypi (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
npm error gyp ERR! stack at async build (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
npm error gyp ERR! stack at async run (/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
npm error gyp ERR! command "/home/gaurav/.nvm/versions/node/v20.17.0/bin/node" "/home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node" "--module_name=queryparser" "--module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm error gyp ERR! cwd /home/gaurav/testgit/node_modules/libpg-query
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok 
npm error node-pre-gyp ERR! build error 
npm error node-pre-gyp ERR! stack Error: Failed to execute '/home/gaurav/.nvm/versions/node/v20.17.0/bin/node /home/gaurav/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gaurav/testgit/node_modules/libpg-query/build/Release/queryparser.node --module_name=queryparser --module_path=/home/gaurav/testgit/node_modules/libpg-query/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gaurav/testgit/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error node-pre-gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
npm error node-pre-gyp ERR! command "/home/gaurav/.nvm/versions/node/v20.17.0/bin/node" "/home/gaurav/testgit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm error node-pre-gyp ERR! cwd /home/gaurav/testgit/node_modules/libpg-query
npm error node-pre-gyp ERR! node -v v20.17.0
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm error node-pre-gyp ERR! not ok
npm error A complete log of this run can be found in: /home/gaurav/.npm/_logs/2024-10-24T10_18_20_133Z-debug-0.log
```

**Comment by DVGY** [comment]
Update: Seems to be working now. Followed this

````
The error you're encountering is due to missing dependencies required for building native modules (node-gyp) on Linux (WSL2 in your case). Specifically, the error mentions that make is not found, which is necessary for compiling C++ addons for Node.js.

Here’s how you can fix it:

Install build tools: Install the necessary build tools (make, gcc, etc.) by running the following command in your WSL2 terminal:

bash
Copy code
sudo apt update
sudo apt install build-essential
Install Python (if not already installed): node-gyp also requires Python. From the log, it seems Python 3.10.12 is detected, but ensure that it's properly configured. If needed, you can install Python using:

bash
Copy code
sudo apt install python3 python3-dev
Retry npm install: After installing the dependencies, try running the npm install command again.

bash
Copy code
npm install
These steps should help resolve the make not found issue and allow node-gyp to build the necessary binaries. Let me know if the issue persists!
````
