### ISSUE TITLE
Deparse error with `ON CONFLICT DO NOTHING`

### ISSUE THREAD

**Issue by ChrisJohnNewton** [constructive-io/pgsql-parser#128]
I received this error stack trace while deparsing the following SQL:

```
INSERT INTO
  public.people (id, name, epithet, is_great, gender, type_id, date_of_birth, date_of_death, place_of_birth, place_of_death, biography, canonical_status_id, image_url, source_url)
VALUES
  (1, 'Asterius', 'of Amasea', FALSE, 'M', 1, '0350-01-01', '0410-01-01', 'Cappadocia', 'Amasea', NULL, 1, NULL, NULL),
  (2, 'Ausonius', NULL, FALSE, 'M', 1, '0310-01-01', '0395-01-01', 'Burdigala', NULL, NULL, NULL, NULL, NULL)
ON CONFLICT DO NOTHING;
```

```
/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:1231
            if (clause.infer.indexElems) {
                             ^

TypeError: Cannot read properties of undefined (reading 'indexElems')
    at Deparser.InsertStmt (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:1231:30)
    at Deparser.deparse (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:281:26)
    at Deparser.RawStmt (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:285:25)
    at Deparser.deparse (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:281:26)
    at /Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:161:33
    at Array.map (<anonymous>)
    at Deparser.deparseQuery (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:161:14)
    at deparse (/Users/chris/Documents/catholica/node_modules/pgsql-deparser/main/deparser.js:146:42)
    at file:///Users/chris/Documents/catholica/database/seeders/seed.js:28:19
```

Line 1231
![image](https://github.com/user-attachments/assets/a9894ecf-3b68-4b04-964e-cd7a14bfb560)

It doesn't seem to like the `ON CONFLICT DO NOTHING` and `clause` has no `infer` property. I've fixed it locally with an optional chain after `infer` for both the if (line 1231) and else if (line 1236).
![image](https://github.com/user-attachments/assets/590607b3-4dc9-42f5-91b1-37b9c0c0721e)

**Comment by pyramation** [comment]
this should be solved! checkout the latest version, pardon the delay, was rebuilding everything from the ground up :)
