### ISSUE TITLE
Cannot install using VS Code terminal

### ISSUE THREAD

**Issue by bfelbo** [constructive-io/pgsql-parser#9]
I use the VS Code terminal for almost everything w/o facing any issues. However, I get the following error while trying to install this package on Node 12 using `npm install pgsql-parser --save-dev` with the VS Code terminal:
```
gyp: Call to 'node -p "require('node-addon-api').gyp"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@12/12.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node@12/12.18.2/bin/node" "/usr/local/Cellar/node@12/12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bfelbo/code/tango/node_modules/@pgql/parse
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pgql/parse@1.2.6 postinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pgql/parse@1.2.6 postinstall script.
```

This is mostly an FYI for anyone else facing this problem. Just use your normal terminal and it works fine.

Feel free to close this issue if you don't want to support the VS Code terminal. It might make sense to support it though as many people use it.

**Comment by pyramation** [comment]
Thanks @bfelbo ... just to confirm, you're able to get everything installed if you use iterm or something else?

**Comment by bfelbo** [comment]
Yep. Everything installed and works fine using the default MacOS terminal.

**Comment by pyramation** [comment]
reopening in case someone else runs into this. Apparently still an issue with VSCode.

**Comment by karlhorky** [comment]
Also ran into a similar problem here: https://github.com/pyramation/libpg-query-node/issues/9#issuecomment-1264691125

Over there it was a `dyld[...]: missing symbol called` error and I came to the conclusion at the time that it was my version of VS Code at first (I have an x64 version of VS Code running via Rosetta 2 on my M1 MacBook).

**Comment by pyramation** [comment]
this should be solved now! check the latest
