### ISSUE TITLE
Error installing the package on Windows 10

### ISSUE THREAD

**Issue by grindarius** [constructive-io/pgsql-parser#95]
I tried to install the package on Windows 10 machine with
- `node` v16.15.1
- `pnpm` 7.23.0
- latest version of `pgsql-parser`
- Visual Studio Community 2019 v16.11.22 with Desktop Development with C++ installed.

The error output is as shown below. The error however *does not* occur when the program when the package is installed in Windows Subsystem For Linux with Ubuntu.

```
D:\coding-projects\ger\packages\ger-sql-to-rust-struct>pnpm i pgsql-parser
../../node_modules/.pnpm/libpg-query@13.3.1/node_modules/libpg-query: Running install script, failed in 4.9s
.../node_modules/libpg-query install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.1-node-v93-win32-x64.tar.gz
│ Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
│   nothing.vcxproj -> D:\coding-projects\ger\node_modules\.pnpm\libpg-query@13.3.1\node_modules\libpg-query\build\Release\\nothing.lib
│   prebuild_dependencies
│   The system cannot find the path specified.
│ C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for '..\binding.gyp' exited with code 1. [D:\coding-p
│ gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onExit (C:\Users\Grindarius\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.23.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\build.js:203:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Windows_NT 10.0.19045
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Grindarius\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\pnpm@7.23.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "buil
│ gyp ERR! cwd D:\coding-projects\ger\node_modules\.pnpm\libpg-query@13.3.1\node_modules\libpg-query
│ gyp ERR! node -v v16.15.1
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Grindarius\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.23.0\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gy
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\coding-projects\ger\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.10\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
│ node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.19045
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\coding-projects\\ger\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.10\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install
│ node-pre-gyp ERR! cwd D:\coding-projects\ger\node_modules\.pnpm\libpg-query@13.3.1\node_modules\libpg-query
│ node-pre-gyp ERR! node -v v16.15.1
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.10
│ node-pre-gyp ERR! not ok
│ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Grindarius\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.23.0\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build
└─ Failed in 4.9s at D:\coding-projects\ger\node_modules\.pnpm\libpg-query@13.3.1\node_modules\libpg-query
 ELIFECYCLE  Command failed with exit code 1.
```

Thank you.

**Comment by pyramation** [comment]
hey sorry! windows is not supported
